<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

    <xacro:include filename="$(find tutorial)/urdf/leg.xacro" />
    <xacro:include filename="$(find tutorial)/urdf/head.xacro" />
    <xacro:include filename="$(find tutorial)/urdf/constants.xacro" />

    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${start_height}" rpy="0 0 0"/>
            <geometry>
                <box size="${robot_body_width*3} ${robot_body_width} ${robot_body_height}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${start_height}" rpy="0 0 0"/>
            <geometry>
                <box size="${robot_body_width*3} ${robot_body_width} ${robot_body_height}"/>
            </geometry>
            <surface>
              <friction>
                <ode>
                  <mu>10000.0</mu>
                  <mu2>10000.0</mu2>
                </ode>
              </friction>
              <contact>
                <ode>
                  <min_depth>0.003</min_depth>
                </ode>
              </contact>
            </surface>
        </collision>
        <inertial>
            <origin xyz="0 0 ${start_height}" rpy="0 0 0"/>
            <mass value="${mass*10}"/>
                  <inertia  
	  ixx="${mass*10 / 12.0 * (robot_body_height*robot_body_height + robot_body_width*robot_body_width)}" ixy="0.0" ixz="0.0"
	  iyy="${mass*10 / 12.0 * (robot_body_height*robot_body_height + (robot_body_width*3)*(3*robot_body_width))}" iyz="0.0"
	  izz="${mass*10 / 12.0 * (robot_body_width*robot_body_width + (robot_body_width*3)*(3*robot_body_width))}"/>
        </inertial>
    </link>

<gazebo reference="base_link">
  <kp>1000000.0</kp>
  <kd>1.0</kd>
  <mu1>0.8</mu1>
  <mu2>0.8</mu2>
  <maxVel>0.0</maxVel>
  <minDepth>0.001</minDepth>
  <material>Gazebo/Orange</material>
</gazebo>

    <xacro:leg prefix="left_back" position="-1" reflect="1" mirror="0" />
    <xacro:leg prefix="left_mid" position="0" reflect="1" mirror="0" />
    <xacro:leg prefix="left_front" position="1" reflect="1" mirror="0" />
    <xacro:leg prefix="right_back" position="-1" reflect="-1" mirror="1" />
    <xacro:leg prefix="right_mid" position="0" reflect="-1" mirror="1" />
    <xacro:leg prefix="right_front" position="1" reflect="-1" mirror="1" />
    
    <!-- Add ROS plugin so we can interact with our robot -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>
</robot>
